### ISSUE TITLE
AEL support is limited

### ISSUE THREAD

**Issue by NSTAdventure** [Aeman105/vmos_resources#2]
Hi aeman please consider about my project:
https://github.com/NSTAdventure/VmosPrivacyRom/issues/1

My project now have very limited support and maybe can dying someday
So for your consideration please think about it
Do you still want to intergrate mine on your  ReaL app? Or want to remove it forever?
Since i didn't have any channel now as my channel already deleted included AEL

Thanks 🙏

**Comment by Aeman105** [comment]
I will still integrate your work. I have already obtained a copy of the
file and am able to generate a direct download with no ads based on the
previous file you shared with me through telegram.

Best regards,
Aeman

**Comment by NSTAdventure** [comment]
> will still integrate your work. I have already obtained a copy of the file and am able to generate a direct download with no ads based on the previous file you shared with me through telegram.

I see but i have request
Since my telegram acc deleted for good
It's related channel and group is also deleted
Mind to replace the ch link with github only?
Also who is creating a group using my AEL channel link?
Mind to check it out and share screenshot?
I see RIP group if i click AEL tg ch link on ReaL app

**Comment by Aeman105** [comment]
I will update this new information in the next update of the ReaL app. Any deleted channels can still be viewed as long as the users have the telegram links. The same goes for Reddit's post. They are not completely deleted. The best way to ensure a complete deletion is to first remove the contents, and then you can remove the channel and group. To my understanding any public channel can be viewed and archived, thus creating a private one is often recommended.  (My email doesn't seem to get through)

**Comment by NSTAdventure** [comment]
> To my understanding any public channel can be viewed and archived, thus creating a private one is often recommended.

Help me about it?
Please check my AEL Channel and send ss what inside i bet smaamx is horsemen of annoyance now 🗿
(Bruh 🗿🗿🗿🗿)

**Comment by Aeman105** [comment]
I will come back and edited this reply with the screenshot in another 4hours.

**Comment by Aeman105** [comment]
What about it?

**Comment by NSTAdventure** [comment]
> What about it?

I thought more msg is exist there 
Okay thanks but one thing pls removey tg ch link i didn't create acc anymore :-)

**Comment by Aeman105** [comment]
@NSTAdventure Alright.

**Comment by NSTAdventure** [comment]
@Aeman105 
I'm found something interesting
Is turned out we can modify Android ID via setedit or such app
![Screenshot_2022-09-22-13-01-30-14](https://user-images.githubusercontent.com/50813528/191670090-43c759b5-e276-4eab-a142-0e65b80b75e2.jpg)

But the thing is i don't know what effect if iwe modify this? 
(Modify = edit, change or delete it)

**Comment by Aeman105** [comment]
This might break any apps' data which require/reference the Android ID, such as MonsterHunterStories which uniquely store its data based on such Android ID.
![Screenshot_2022-09-22-14-37-04-760_rikka appops](https://user-images.githubusercontent.com/109656167/191675688-4a21fccc-1195-4e76-a436-09867f0822d4.png)

**Comment by Aeman105** [comment]
Please submit a new issue to discuss this, or use the one i opened

**Comment by Aeman105** [comment]
I will update this new information in the next update of the ReaL app. Any
deleted channels can still be viewed as long as the users have the telegram
links. The same goes for Reddit's post. They are not completely deleted.
The best way to ensure a complete deletion is to first remove the contents,
and then you can remove the channel and group. To my understanding any
public channel can be viewed and archived, thus creating a private one is
often recommended.
