### ISSUE TITLE
Android ID

### ISSUE THREAD

**Issue by Aeman105** [Aeman105/vmos_resources#4]
@Aeman105 
I'm found something interesting
Is turned out we can modify Android ID via setedit or such app
![Screenshot_2022-09-22-13-01-30-14](https://user-images.githubusercontent.com/50813528/191670090-43c759b5-e276-4eab-a142-0e65b80b75e2.jpg)

But the thing is i don't know what effect if iwe modify this? 
(Modify = edit, change or delete it)

Can you help me figure this out? 
🙏🤔

_Originally posted by @NSTAdventure in https://github.com/Aeman105/vmos_resources/issues/2#issuecomment-1254567851_

**Comment by NSTAdventure** [comment]
Bruh 🥴
Did you found something yet?
:-/

**Comment by Aeman105** [comment]
Yes. Read this: https://android.gadgethacks.com/how-to/keep-apps-from-collecting-data-about-your-phone-by-spoofing-device-id-values-0337231/

**Comment by NSTAdventure** [comment]
> Yes. Read this: https://android.gadgethacks.com/how-to/keep-apps-from-collecting-data-about-your-phone-by-spoofing-device-id-values-0337231/

Gadget hack be like:
Required root 
(Bruh 🗿🗿🗿🗿)

**Comment by Aeman105** [comment]
There are always other alternatives for this. Like you said by using tool such as SetEdit, virtual environment such as VirtualXposed, or simply installing those apps inside a VM.

**Comment by NSTAdventure** [comment]
> There are always other alternatives for this. Like you said by using tool such as SetEdit, virtual environment such as VirtualXposed, or simply installing those apps inside a VM.

1. Removal of Android ID maybe isn't affect UID 
(In your deleted reply you said it will affecting permission or something like that)

Where is that reply?

**Comment by Aeman105** [comment]
@NSTAdventure I haven't deleted anything. Please read carefully.

**Comment by NSTAdventure** [comment]
> @NSTAdventure I haven't deleted anything. Please read carefully.
Apologize for my mistake sir

I forgot you posted that on previous AEL issues 🙏😅
