### ISSUE TITLE
Vmos the horsement of the annoyance 🗿

### ISSUE THREAD

**Issue by NSTAdventure** [Aeman105/vmos_resources#5]
Sir i have problem with vmos

1. All custom rom that are rec / import always can't load xposed with error couldn't load zip file blah blah blah

2. How the heck i can install gapps now?

Now how i can solve those horsemen of the annoyance sir? That's causing pain 💀

**Comment by Aeman105** [comment]
@NSTAdventure This has been an issue starting VMOSPro v2.8.x

**Comment by NSTAdventure** [comment]
> @NSTAdventure This has been an issue starting VMOSPro v2.8.x

Welp is there a way to at least temporary fix the problem?

Also please take note about xposed issues on me it's happening to all vm that i tried on my devices

**Comment by Aeman105** [comment]
@NSTAdventure Then I would suggest you to try Sesshoumaru81's custom rom from 4pda: https://4pda.to/forum/index.php?showtopic=961828&st=11100

**Comment by Aeman105** [comment]
@NSTAdventure But at the very least you should see his work.

Here are some youtube videos showing even with custom roms, he managed to import/rec the rom with perfect recovery with working root/xposed/gms. This had been tested on multiple devices even those running A12+

1-https://youtu.be/Rgs32oAiuB0
2-https://youtu.be/IOhs-644fVo
3-https://youtu.be/t-Bog78mJRY
4-https://youtu.be/zFS1fjwC_Ck

**Comment by NSTAdventure** [comment]
> @NSTAdventure Then I would suggest you to try Sesshoumaru81's custom rom from 4pda: https://4pda.to/forum/index.php?showtopic=961828&st=11100

![Screenshot_2022-11-05-19-50-33-29.jpg](https://user-images.githubusercontent.com/50813528/200120779-a631b605-aaf2-4c78-8d7b-82ef1da9158f.jpg)
![Screenshot_2022-11-05-19-50-47-16.jpg](https://user-images.githubusercontent.com/50813528/200120782-739d8fc5-4a4b-4922-b079-d1d58845832a.jpg)
Bruh 🗿🗿🗿🗿

**Comment by Aeman105** [comment]
@NSTAdventure The file is a 7z format and VMOSPro doesn't and couldn't read or detect that specific format. Please convert the rom to a Zip format using this tool called PowerISO:
https://www.poweriso.com/tutorials/index.html/

After completing the file conversion to Zip format, use import button to have the custom rom installed into VMOSPro.

Please do your own personal testing before asking any more questions that can easily be answered if you do your personal research.

**Comment by NSTAdventure** [comment]
> The file is a 7z format and VMOSPro doesn't and couldn't read or detect that specific format. Please convert the rom to a Zip format using this tool called PowerISO: https://www.poweriso.com/tutorials/index.html/
> 
> After completing the file conversion to Zip format, use import button to have the custom rom installed into VMOSPro.

Ok sir



> Please do your own personal testing before asking any more questions that can easily be answered if you do your personal research.

Bro 💀
I won't bothering anyone else with those low effort question if i already found my answer on google 💀
![Screenshot_2022-11-06-07-48-32-18](https://user-images.githubusercontent.com/50813528/200148880-0c1f8ee6-e89f-4eab-b00d-b4784180c5a0.jpg)
![Screenshot_2022-11-06-07-48-39-79](https://user-images.githubusercontent.com/50813528/200148889-e4f432f3-c390-4a8a-9c77-02efa0900cbc.jpg)
See? That's just for real devices not vm's and i couldn't found any info regarding to vm's 💀

no don't close and lock this conversation pls i am not done yet :-(

**Comment by Aeman105** [comment]
@NSTAdventure You misunderstood me. Anyways.

Please follow this steps:
1. Complete the rom conversion into Zip format
2. Extract xposed zip files shared by mrfrost475 in Android_VMs_Chat group
3. Copy everything in the extracted system folder except the system/app folder.
4. Rec/import rom
5. Install the xposed installer app

**Comment by NSTAdventure** [comment]
> 2. Extract xposed zip files shared by mrfrost475 in Android_VMs_Chat group

Welp for mrfrost rom mind to share here or it's available on your ReaL app?
You forgot if i quit from tg
(or i didn't tell you before)

**Comment by Aeman105** [comment]
@NSTAdventure Everything should be available on RL app v1.3.1. All direct links will not work as it seems to only work for a short period of time. Those direct links will not be maintained and supervised as it seems not that many people seem to be using it. I will, in the future, add the actual URL links to the files rather than provided a direct link for those files.

Note: All direct links are created by an automated bot.

**Comment by Aeman105** [comment]
@Aeman105 Here are all the xposed files shared by mrfrost475 on Telegram. Bear in mind, this links will not last long. It's best for you to download all these files quick as I will not always be able to generate the links.

**Comment by Aeman105** [comment]
@NSTAdventure Android 7 32bit xposed files
https://webstreamx.herokuapp.com/download/2867458

Android 7 64bit xposed files
https://webstreamx.herokuapp.com/download/2867459

Android 5 64bit xposed files
https://webstreamx.herokuapp.com/download/2867425

Android 5 32bit xposed files
https://webstreamx.herokuapp.com/download/2867426

**Comment by NSTAdventure** [comment]
> @NSTAdventure Android 7 32bit xposed files
> https://webstreamx.herokuapp.com/download/2867458
> 
> Android 7 64bit xposed files
> https://webstreamx.herokuapp.com/download/2867459
> 
> Android 5 64bit xposed files
> https://webstreamx.herokuapp.com/download/2867425
> 
> Android 5 32bit xposed files
> https://webstreamx.herokuapp.com/download/2867426


Issues closed 
Fixing vmos is shit i can't understand every single of android structure as i mentioned here:
https://t.me/c/1506053945/42071

I used X8 Sandbox instead 
Xposed still error but at least not with the root 🥴🗿
